#!/bin/bash

# ClamAV Otomatik Kurulum ve Yapılandırma Scripti
# Bu script tüm ClamAV yapılandırmalarını otomatik olarak kurar

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

if [ "$EUID" -ne 0 ]; then
    print_error "Bu script root yetkisi ile çalıştırılmalıdır."
    exit 1
fi

print_info "ClamAV Otomatik Kurulum Başlatılıyor..."

print_info "Gerekli paketler kuruluyor..."
apt-get update
apt-get install -y clamav clamav-daemon clamav-freshclam inotify-tools

print_info "ClamAV servisleri yapılandırma için durduruluyor..."
systemctl stop clamav-freshclam
systemctl stop clamav-daemon

print_info "Karantina dizinleri oluşturuluyor..."
mkdir -p /var/log/clamav/quarantine/realtime
mkdir -p /var/log/clamav/quarantine/daily
chmod -R 755 /var/log/clamav/quarantine

print_info "Log dizinleri oluşturuluyor..."
mkdir -p /var/log/clamav
chmod 755 /var/log/clamav

print_info "Realtime izleme scripti oluşturuluyor..."
cat > /usr/local/bin/clamav-watch.sh << 'EOF'
#!/bin/bash
WATCH_DIR="/home"
LOG_FILE="/var/log/clamav/clamav-watch.log"
QUARANTINE_DIR="/var/log/clamav/quarantine/realtime"

touch "$LOG_FILE"
chmod 644 "$LOG_FILE"

inotifywait -m -r -e create -e modify -e move -e close_write -e delete "$WATCH_DIR" --format '%w%f|%e' | while IFS='|' read -r FILE EVENT
do
    echo "$(date): Event $EVENT on $FILE" >> "$LOG_FILE"
    sudo clamdscan --fdpass --move="$QUARANTINE_DIR" "$FILE" >> "$LOG_FILE" 2>&1
done
EOF

chmod +x /usr/local/bin/clamav-watch.sh

print_info "Systemd servis dosyası oluşturuluyor..."
cat > /etc/systemd/system/clamav-watch.service << 'EOF'
[Unit]
Description=ClamAV Watch Directory Scanner
After=network.target clamav-freshclam.service

[Service]
Type=simple
ExecStart=/usr/local/bin/clamav-watch.sh
RestartSec=5
Restart=always
User=root
Group=root
StandardOutput=append:/var/log/clamav/clamav-watch.log
StandardError=append:/var/log/clamav/clamav-watch.log

[Install]
WantedBy=multi-user.target
EOF

print_info "ClamAV yapılandırma dosyası güncelleniyor..."
cat > /etc/clamav/clamd.conf << 'EOF'
#Automatically Generated by clamav-daemon postinst
#To reconfigure clamav-daemon run #dpkg-reconfigure clamav-daemon
#Please read /usr/share/doc/clamav-daemon/README.Debian.gz for details
LocalSocket /var/run/clamav/clamd.ctl
FixStaleSocket yes
LocalSocketGroup clamav
LocalSocketMode 666
# TemporaryDirectory is not set to its default /tmp here to make overriding
# the default with environment variables TMPDIR/TMP/TEMP possible
User root
ScanMail yes
ScanArchive yes
ArchiveBlockEncrypted no
MaxDirectoryRecursion 15
FollowDirectorySymlinks no
FollowFileSymlinks no
ReadTimeout 180
MaxThreads 24
MaxConnectionQueueLength 30
LogSyslog no
LogRotate yes
LogFacility LOG_LOCAL6
LogClean yes
LogVerbose no
PreludeEnable no
PreludeAnalyzerName ClamAV
DatabaseDirectory /var/lib/clamav
OfficialDatabaseOnly no
SelfCheck 3600
Foreground no
Debug no
ScanPE yes
MaxEmbeddedPE 10M
ScanOLE2 yes
ScanPDF yes
ScanHTML yes
MaxHTMLNormalize 10M
MaxHTMLNoTags 2M
MaxScriptNormalize 5M
MaxZipTypeRcg 1M
ScanSWF yes
ExitOnOOM no
LeaveTemporaryFiles no
AlgorithmicDetection yes
ScanELF yes
IdleTimeout 30
CrossFilesystems yes
PhishingSignatures yes
PhishingScanURLs yes
PhishingAlwaysBlockSSLMismatch no
PhishingAlwaysBlockCloak no
PartitionIntersection no
DetectPUA no
ScanPartialMessages no
HeuristicScanPrecedence no
StructuredDataDetection no
CommandReadTimeout 30
SendBufTimeout 200
MaxQueue 100
ExtendedDetectionInfo yes
OLE2BlockMacros no
AllowAllMatchScan yes
ForceToDisk no
DisableCertCheck no
DisableCache no
MaxScanTime 120000
MaxScanSize 2G
MaxFileSize 2G
MaxRecursion 25
MaxFiles 10000
MaxPartitions 50
MaxIconsPE 100
PCREMatchLimit 10000
PCRERecMatchLimit 5000
PCREMaxFileSize 25M
ScanXMLDOCS yes
ScanHWP3 yes
MaxRecHWP3 16
StreamMaxLength 2G
LogFile /var/log/clamav/clamav.log
LogTime yes
LogFileUnlock no
LogFileMaxSize 0
Bytecode yes
BytecodeSecurity TrustSigned
BytecodeTimeout 60000
OnAccessMaxFileSize 5M
EOF

print_info "Günlük tarama scripti oluşturuluyor..."
cat > /usr/local/bin/clamav-fullscan.sh << 'EOF'
#!/bin/bash

SCAN_DIR="/home"
QUARANTINE_DIR="/var/log/clamav/quarantine/daily"
LOG_FILE="/var/log/clamav/clamav-viruses.log"

touch "$LOG_FILE"
chmod 644 "$LOG_FILE"

SCAN_RESULT=$(sudo clamdscan --fdpass --move="$QUARANTINE_DIR" "$SCAN_DIR" 2>/dev/null)

if echo "$SCAN_RESULT" | grep -q "Infected files: [1-9]"; then
    echo "$(date): Infected files found. Moved to quarantine:" >> "$LOG_FILE"
    echo "$SCAN_RESULT" | grep " -> $QUARANTINE_DIR" >> "$LOG_FILE"
fi
EOF

chmod +x /usr/local/bin/clamav-fullscan.sh

print_info "Logrotate yapılandırması oluşturuluyor..."
cat > /etc/logrotate.d/clamav-watch << 'EOF'
/var/log/clamav/clamav-watch.log {
    daily
    rotate 7
    missingok
    notifempty
    compress
    delaycompress
    create 640 root adm
}

/var/log/clamav/clamav-viruses.log {
    daily
    rotate 7
    missingok
    notifempty
    compress
    delaycompress
    create 640 root adm
}
EOF

# her gün 12:00'de full scan
print_info "Cron job ekleniyor..."
(crontab -l 2>/dev/null | grep -v "/usr/local/bin/clamav-fullscan.sh"; echo "0 12 * * * /usr/local/bin/clamav-fullscan.sh") | crontab -

print_info "ClamAV veritabanı güncelleniyor..."
freshclam

print_info "ClamAV servisleri başlatılıyor..."
systemctl daemon-reload
systemctl start clamav-freshclam
systemctl start clamav-daemon
systemctl enable clamav-freshclam
systemctl enable clamav-daemon

print_info "ClamAV Watch servisi başlatılıyor..."
systemctl enable clamav-watch.service
systemctl start clamav-watch.service

chown -R clamav:clamav /var/lib/clamav
chown -R clamav:clamav /var/log/clamav

print_info "ClamAV kurulumu başarıyla tamamlandı!"
print_info "Kurulan bileşenler:"
print_info "  - Realtime izleme: /usr/local/bin/clamav-watch.sh"
print_info "  - Günlük tarama: /usr/local/bin/clamav-fullscan.sh"
print_info "  - Systemd servisi: /etc/systemd/system/clamav-watch.service"
print_info "  - Karantina dizinleri: /var/log/clamav/quarantine/realtime ve /var/log/clamav/quarantine/daily"
print_info "  - Logrotate yapılandırması: /etc/logrotate.d/clamav-watch"
print_info "  - Cron job: Her gün 12:00'de tam tarama"

print_info "Servis durumları kontrol ediliyor..."
systemctl status clamav-daemon --no-pager
echo ""
systemctl status clamav-watch.service --no-pager

print_info "Kurulum tamamlandı. Tüm yapılandırmalar başarıyla uygulandı."

